export const Dummy = [
  {
    id: 1,
    images: ['https://i.dummyjson.com/data/products/1/1.jpg'],
    price: 549,
    title: 'iPhone 9',
  },
  {
    id: 2,
    images: ['https://i.dummyjson.com/data/products/2/1.jpg'],
    price: 899,
    title: 'iPhone X',
  },
  {
    id: 3,
    images: ['https://i.dummyjson.com/data/products/3/1.jpg'],
    price: 1249,
    title: 'Samsung Universe 9',
  },
  {
    id: 4,
    images: ['https://i.dummyjson.com/data/products/4/1.jpg'],
    price: 280,
    title: 'OPPOF19',
  },
  {
    id: 5,
    images: ['https://i.dummyjson.com/data/products/5/1.jpg'],
    price: 499,
    title: 'Huawei P30',
  },
  {
    id: 6,
    images: [
      'https://i.dummyjson.com/data/products/13/1.jpg',
      'https://i.dummyjson.com/data/products/13/2.png',
      'https://i.dummyjson.com/data/products/13/3.jpg',
      'https://i.dummyjson.com/data/products/13/4.jpg',
      'https://i.dummyjson.com/data/products/13/thumbnail.webp',
    ],
    price: 13,
    title: 'Fog Scent Xpressio Perfume',
  },
  {
    id: 7,
    images: [
      'https://i.dummyjson.com/data/products/14/1.jpg',
      'https://i.dummyjson.com/data/products/14/2.jpg',
      'https://i.dummyjson.com/data/products/14/3.jpg',
      'https://i.dummyjson.com/data/products/14/thumbnail.jpg',
    ],
    price: 120,
    title: 'Non-Alcoholic Concentrated Perfume Oil',
  },
  {
    id: 8,
    images: [
      'https://i.dummyjson.com/data/products/15/1.jpg',
      'https://i.dummyjson.com/data/products/15/2.jpg',
      'https://i.dummyjson.com/data/products/15/3.jpg',
      'https://i.dummyjson.com/data/products/15/4.jpg',
      'https://i.dummyjson.com/data/products/15/thumbnail.jpg',
    ],
    price: 30,
    title: 'Eau De Perfume Spray',
  },
  {
    id: 9,
    images: [
      'https://i.dummyjson.com/data/products/16/1.png',
      'https://i.dummyjson.com/data/products/16/2.webp',
      'https://i.dummyjson.com/data/products/16/3.jpg',
      'https://i.dummyjson.com/data/products/16/4.jpg',
      'https://i.dummyjson.com/data/products/16/thumbnail.jpg',
    ],
    price: 19,
    title: 'Hyaluronic Acid Serum',
  },
  {
    id: 10,
    images: [
      'https://i.dummyjson.com/data/products/17/1.jpg',
      'https://i.dummyjson.com/data/products/17/2.jpg',
      'https://i.dummyjson.com/data/products/17/3.jpg',
      'https://i.dummyjson.com/data/products/17/thumbnail.jpg',
    ],
    price: 12,
    title: 'Tree Oil 30ml',
  },
  {
    id: 11,
    images: [
      'https://i.dummyjson.com/data/products/18/1.jpg',
      'https://i.dummyjson.com/data/products/18/2.jpg',
      'https://i.dummyjson.com/data/products/18/3.jpg',
      'https://i.dummyjson.com/data/products/18/4.jpg',
      'https://i.dummyjson.com/data/products/18/thumbnail.jpg',
    ],
    price: 40,
    title: 'Oil Free Moisturizer 100ml',
  },
  {
    id: 12,
    images: [
      'https://i.dummyjson.com/data/products/19/1.jpg',
      'https://i.dummyjson.com/data/products/19/2.jpg',
      'https://i.dummyjson.com/data/products/19/3.png',
      'https://i.dummyjson.com/data/products/19/thumbnail.jpg',
    ],
    price: 46,
    title: 'Skin Beauty Serum.',
  },
  {
    id: 13,
    images: [
      'https://i.dummyjson.com/data/products/20/1.jpg',
      'https://i.dummyjson.com/data/products/20/2.jpg',
      'https://i.dummyjson.com/data/products/20/3.jpg',
      'https://i.dummyjson.com/data/products/20/4.jpg',
      'https://i.dummyjson.com/data/products/20/thumbnail.jpg',
    ],
    price: 70,
    title: 'Freckle Treatment Cream- 15gm',
  },
];
